pipeline
{
  agent any
  stages
  { 
    stage("git clone")
    { 
      steps{
        script{
        
      git "https://github.com/SaiPranavReddy/OnlineShopRepo.git"
    }
      }
    }
    def pompath = "OnlineShopSpringRESTFulSpringBootJPA/"
dir(pompath)
{
    stage("mvn clean")
    {
      steps{
        script{
          
        bat "mvn clean"
    }
      }
    }
}
  }
}
