pipeline
{
  agent any
  stages
  { 
    stage("git clone")
    { 
      steps{
        script{
        
      git "https://github.com/SaiPranavReddy/OnlineShopRepo.git"
    }
      }
    }
   // def pompath = "OnlineShopSpringRESTFulSpringBootJPA/"


    stage("mvn clean")
    {
      steps{
          dir("OnlineShopSpringRESTFulSpringBootJPA/"){
        
        
        script{
          
        bat "mvn clean"
    }
          }
      }
    }

  }
}
