node
{
    stage("git clone")
    {
        git "https://github.com/SaiPranavReddy/OnlineShopRepo.git"

    }
    dir("OnlineShopSpringRESTFulSpringBootJPA/"){
        stage("mvn clean")
        {
            bat "mvn clean"
        }
    }
}
